//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntilopeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Articulos()
        {
            this.Pedidos_Detalle = new HashSet<Pedidos_Detalle>();
        }
    
        public long SKU { get; set; }
        public string Descripcion { get; set; }
        public string Medida { get; set; }
        public string Unidad { get; set; }
        public Nullable<int> Id_SubCategoria { get; set; }
        public string StrImagen { get; set; }
        public Nullable<bool> Oferta { get; set; }
        public string StrImagenBig { get; set; }
        public string StrImagenSec1 { get; set; }
        public string StrImagenSec2 { get; set; }
        public string StrImagenSec3 { get; set; }
        public string StrImagenSec4 { get; set; }
        public string StrImagenSec5 { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<decimal> Precio_Venta { get; set; }
        public Nullable<decimal> Precio_Oferta { get; set; }
        public Nullable<bool> Habilitado { get; set; }
        public Nullable<System.DateTime> FechaUltModif { get; set; }
        public Nullable<System.DateTime> Oferta_FechaInicio { get; set; }
        public Nullable<System.DateTime> Oferta_FechaFin { get; set; }
        public Nullable<bool> Oferta_Vigente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos_Detalle> Pedidos_Detalle { get; set; }
    }
}
