//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntilopeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos_Detalle
    {
        public int Id { get; set; }
        public Nullable<int> idPedido { get; set; }
        public Nullable<long> SKU { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    
        public virtual Articulos Articulos { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
