//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntilopeWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.Pedidos_Detalle = new HashSet<Pedidos_Detalle>();
        }
    
        public int IdPedido { get; set; }
        public Nullable<int> idSucursal { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<System.DateTime> Fecha_Compra { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<System.DateTime> Fecha_Entrega { get; set; }
        public string Hora_Desde { get; set; }
        public string Hora_Hasta { get; set; }
        public string preference_id { get; set; }
        public Nullable<int> IdTipoPago { get; set; }
        public string FormaEntrega { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos_Detalle> Pedidos_Detalle { get; set; }
    }
}
